name: Test package

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel scmver setuptools setuptools-scm

    - name: Get version from setup.py
      id: version
      run: |
        version=$(python -m setuptools_scm)
        echo "version=$version" >> $GITHUB_ENV

    - name: Build package
      run: python -m build

    - name: Install package
      run: pip install dist/yardstiq_scaleway-${version}-py3-none-any.whl

    - name: Install test
      run: pip install -r tests/requirements.txt

    - name: Run test
      run: pytest -s --showprogress -vv tests/
      env:
        YARDSTIQ_SCALEWAY_PROJECT_ID: ${{ secrets.STG_YARDSTIQ_SCALEWAY_PROJECT_ID }}
        YARDSTIQ_SCALEWAY_SECRET_KEY: ${{ secrets.STG_YARDSTIQ_SCALEWAY_API_TOKEN }}
        YARDSTIQ_SCALEWAY_API_URL: ${{ secrets.STG_YARDSTIQ_SCALEWAY_API_URL }}